import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import data from '../public/data/preguntas.json'

export default function Home() {

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {data.preguntas.map(item => (
                    <>
                        <p key={item.id}>{item.tema}</p>
                        {item.preguntas.map((item, i) =>
                            <div key={item.id} className={styles.preguntas}>
                                <p className={styles.preguntas}>{i + 1} - {item.pregunta}</p>
                                <div className={styles.radio}>
                                    <div>
                                        <label htmlFor='sí'>Sí</label>
                                        <input type='radio' id="sí" name={item.id} />
                                    </div>
                                    <div>
                                        <label htmlFor='no'>No</label>
                                        <input type='radio' id="no" name={item.id} />
                                    </div>
                                </div>
                            </div>
                        )}
                    </>
                )
                )}
            </main>

        </div>
    )
}
